
package servidor.publicar;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "CorreoNoEncontradoException", targetNamespace = "http://publicar.servidor/")
public class CorreoNoEncontradoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CorreoNoEncontradoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CorreoNoEncontradoException_Exception(String message, CorreoNoEncontradoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public CorreoNoEncontradoException_Exception(String message, CorreoNoEncontradoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.publicar.CorreoNoEncontradoException
     */
    public CorreoNoEncontradoException getFaultInfo() {
        return faultInfo;
    }

}
