
package servidor.publicar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServicioOfertasService", targetNamespace = "http://publicar.servidor/", wsdlLocation = "http://pcunix73.fing.edu.uy:9128/servicioofertas?wsdl")
public class ServicioOfertasService
    extends Service
{

    private final static URL SERVICIOOFERTASSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOOFERTASSERVICE_EXCEPTION;
    private final static QName SERVICIOOFERTASSERVICE_QNAME = new QName("http://publicar.servidor/", "ServicioOfertasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://pcunix73.fing.edu.uy:9128/servicioofertas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOOFERTASSERVICE_WSDL_LOCATION = url;
        SERVICIOOFERTASSERVICE_EXCEPTION = e;
    }

    public ServicioOfertasService() {
        super(__getWsdlLocation(), SERVICIOOFERTASSERVICE_QNAME);
    }

    public ServicioOfertasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOOFERTASSERVICE_QNAME, features);
    }

    public ServicioOfertasService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOOFERTASSERVICE_QNAME);
    }

    public ServicioOfertasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOOFERTASSERVICE_QNAME, features);
    }

    public ServicioOfertasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioOfertasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioOfertas
     */
    @WebEndpoint(name = "ServicioOfertasPort")
    public ServicioOfertas getServicioOfertasPort() {
        return super.getPort(new QName("http://publicar.servidor/", "ServicioOfertasPort"), ServicioOfertas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioOfertas
     */
    @WebEndpoint(name = "ServicioOfertasPort")
    public ServicioOfertas getServicioOfertasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicar.servidor/", "ServicioOfertasPort"), ServicioOfertas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOOFERTASSERVICE_EXCEPTION!= null) {
            throw SERVICIOOFERTASSERVICE_EXCEPTION;
        }
        return SERVICIOOFERTASSERVICE_WSDL_LOCATION;
    }

}
