
package servidor.publicar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServicioUsuariosService", targetNamespace = "http://publicar.servidor/", wsdlLocation = "http://pcunix73.fing.edu.uy:9128/serviciousuarios?wsdl")
public class ServicioUsuariosService
    extends Service
{

    private final static URL SERVICIOUSUARIOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOUSUARIOSSERVICE_EXCEPTION;
    private final static QName SERVICIOUSUARIOSSERVICE_QNAME = new QName("http://publicar.servidor/", "ServicioUsuariosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://pcunix73.fing.edu.uy:9128/serviciousuarios?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOUSUARIOSSERVICE_WSDL_LOCATION = url;
        SERVICIOUSUARIOSSERVICE_EXCEPTION = e;
    }

    public ServicioUsuariosService() {
        super(__getWsdlLocation(), SERVICIOUSUARIOSSERVICE_QNAME);
    }

    public ServicioUsuariosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOUSUARIOSSERVICE_QNAME, features);
    }

    public ServicioUsuariosService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOUSUARIOSSERVICE_QNAME);
    }

    public ServicioUsuariosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOUSUARIOSSERVICE_QNAME, features);
    }

    public ServicioUsuariosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioUsuariosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioUsuarios
     */
    @WebEndpoint(name = "ServicioUsuariosPort")
    public ServicioUsuarios getServicioUsuariosPort() {
        return super.getPort(new QName("http://publicar.servidor/", "ServicioUsuariosPort"), ServicioUsuarios.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioUsuarios
     */
    @WebEndpoint(name = "ServicioUsuariosPort")
    public ServicioUsuarios getServicioUsuariosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicar.servidor/", "ServicioUsuariosPort"), ServicioUsuarios.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOUSUARIOSSERVICE_EXCEPTION!= null) {
            throw SERVICIOUSUARIOSSERVICE_EXCEPTION;
        }
        return SERVICIOUSUARIOSSERVICE_WSDL_LOCATION;
    }

}
